version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: portal
    ports:
      - "3306:3306"
    networks:
      - app-network

  node-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
